### PR TITLE
fix: cache reader to prevent locking

### LINKED ISSUE #40: [BUG] Supabase: Cannot read request.body contents
In Supabase functions `Request.body` cannot be read ever.

Taking this as a base example it always return "`Body not used`" (independently if you send body in your post request or not:

Example cURL: 
```bash
curl  -X POST -d '{"message":"This is a test"}' http://localhost:54321/functions/v1/dart_edge
```

`main.dart`

```dart
import 'package:supabase_functions/supabase_functions.dart';

void main() {
  SupabaseFunctions(fetch: (request) {
    if (request.bodyUsed) {
      return Response("Body used! - Contents: ${request.body}");
    } else {
      return Response("Body not used");
    }
  });
}
```

If you try to read the body directly there is an error: 

```dart
import 'package:supabase_functions/supabase_functions.dart';

void main() {
  SupabaseFunctions(fetch: (request) {
    if (request.body != null) { // accesing body directly
      return Response("Body used! - Contents: ${request.body}");
    } else {
      return Response("Body not used");
    }
  });
}
```

```js
UnknownJsTypeError {
  "__js_helper$_message": "ReadableStream is locked.",
  "$thrownJsError": TypeError: ReadableStream is locked.
    at setUpReadableStreamDefaultReader (internal:ext/web/06_streams.js:3357:13)
    at new ReadableStreamDefaultReader (internal:ext/web/06_streams.js:4933:7)
    at acquireReadableStreamDefaultReader (internal:ext/web/06_streams.js:297:12)
    at ReadableStream.getReader (internal:ext/web/06_streams.js:4781:16)
    at Request.get$body (file:///home/deno/functions/dart_edge/main.dart.js:7414:89)
    at main_closure.call$1 (file:///home/deno/functions/dart_edge/main.dart.js:7424:68)
    at file:///home/deno/functions/dart_edge/main.dart.js:7466:60
    at _wrapJsFunctionForAsync_closure.$protected (file:///home/deno/functions/dart_edge/main.dart.js:2948:15)
    at _wrapJsFunctionForAsync_closure.call$2 (file:///home/deno/functions/dart_edge/main.dart.js:5575:12)
    at Object._asyncStartSync (file:///home/deno/functions/dart_edge/main.dart.js:2912:20)
}
```

### PR DESCRIPTION
**Pull request by lesnitsky**
Closes #40

### CODE REVIEW

**Comment by henry2man** [comment]
I've installed edge manually using this branch but I'm still having errors:

```
Check file:///home/deno/functions/dart_edge/index.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux aarch64
Version: 1.30.3
Args: ["deno", "run", "--no-check=remote", "--allow-all", "--watch", "--no-clear-screen", "--no-npm", "/home/deno/functions/dart_edge/index.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /deno/serde_v8/de.rs:630:53
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Stopped serving supabase/functions/dart_edge
```

`request.bodyUsed` is still `false`, this Panic occurs if I try to check that `request.body != null`

**Comment by henry2man** [comment]
@lesnitsky did you check the example function I've posted? I think there is an underlying issue

**Comment by lesnitsky** [comment]
@henry2man yes, I've checked your function and it worked for me. Make sure to make a clean install.
How did you install dart_edge from there branch?

**Comment by lesnitsky** [comment]
I can't see `git checkout fix/request-body-access` in your steps

**Comment by henry2man** [comment]
Just to add context: I'm on an standard ubuntu 22.10 ubuntu server instance. Prior to this I've followed this tutorial: https://www.youtube.com/watch?v=53jhgrDONW4

**Comment by lesnitsky** [comment]
did you also update a `supabase_functions` dependency to point to the branch? What is your `pubspec.yaml`?
deactivating `edge` globally and linking a CLI to a local checkout is not enough (and unnecessary), since the change is related to the `edge_runtime`, not cli package

**Comment by henry2man** [comment]
Ok, I've reverted edge to published version and I've adjusted `pubspec.yaml` like this. Is this what you mean?

```
name: supabase_edge_functions_example
description: A Supaabase Edge Functions example written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  edge: ^0.0.5
  supabase_functions: 
    git:
      url: https://github.com/invertase/dart_edge.git
      ref: fix/request-body-access

dev_dependencies:
  lints: ^2.0.1
```

**Comment by henry2man** [comment]
Confirmed, works like a charm. Can be merged! 🚀

**Pull request merged**
